spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kiranh2195/configuration_properties.git
          clone-on-start: true  
           
management:
  security:
    enabled: false           