server:
  port: 3333
spring:
  application:
    name: API-GATEWAY 

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true 
      routes:
      - id: one                              
        uri: lb://WELCOME-API              
        predicates:
        - Path=/welcome            
      - id: two
        uri: lb://Greet-API
        predicates:
        - Path=/greet